package afas

var connectors = map[string][]struct {
	Name        string
	Description string
}{
	"General": {
		{Name: "KnUser", Description: "Users"},
		{Name: "KnCustomK01", Description: "Custom files"},
		{Name: "KnCustomK02", Description: "Custom files"},
		{Name: "KnCustomK03", Description: "Custom files"},
		{Name: "KnCustomK04", Description: "Custom files"},
		{Name: "KnCustomK05", Description: "Custom files"},
		{Name: "KnCustomK06", Description: "Custom files"},
		{Name: "KnCustomK07", Description: "Custom files"},
		{Name: "KnCustomK08", Description: "Custom files"},
		{Name: "KnCustomK09", Description: "Custom files"},
		{Name: "KnCustomK10", Description: "Custom files"},
		{Name: "KnCustomLinkCxx", Description: "Custom contact files"},
	},
	"CRM": {
		{Name: "KnPerson", Description: "Persons"},
		{Name: "KnOrganisation", Description: "Organisations /contacts"},
		{Name: "KnContact", Description: "Change contacts"},
		{Name: "KnSubject", Description: "Dossies items"},
		{Name: "KnSubjectWorkflowReaction", Description: "Response to dossier item or forwarding a dossier item in a workflow"},
		{Name: "KnCoursGroupLines", Description: "Course planning"},
		{Name: "KnCourseMember", Description: "Course participants"},
		{Name: "KnCourseSessionMember", Description: "Participants in a session"},
		{Name: "KnCourseEvent", Description: "Events and sessions"},
		{Name: "KnProvApplication", Description: "Deviating issue methods by organisation/person"},
		{Name: "CmForecast", Description: "Forecasts "},
	},
	"Financial": {
		{Name: "KnSalesRelationOrg", Description: "Sales contacts"},
		{Name: "KnSalesRelationPer", Description: "Sales contacts"},
		{Name: "KnPurchaseRelationOrg", Description: "Purchase contacts "},
		{Name: "KnPurchaseRelationPer", Description: "Purchase contacts "},
		{Name: "KnAccount", Description: "Ledger accounts"},
		{Name: "KnDimCode", Description: "Allocation codes"},
		{Name: "FiEntries", Description: "Ledger entries"},
		{Name: "FiBudget", Description: "Budgets"},
		{Name: "FiInvoice", Description: "Financial invoices "},
		{Name: "KnCurrencyRates", Description: "Current rates"},
		{Name: "FiSepaDirectDebit", Description: "SEPA collection mandates "},
		{Name: "KnBankTransaction", Description: "Bank transaction codes"},
		{Name: "FiContract", Description: "Contracts"},
		{Name: "FiReservation", Description: "Reservations"},
		{Name: "FiCommitment", Description: "Obligations"},
		{Name: "FiProcuration", Description: "Procuration lines"},
		{Name: "FiFixedAssets", Description: "Fixed assets"},
	},
	"HR": {
		{Name: "KnEmployee", Description: "Employees"},
		{Name: "HrApplicant", Description: "Applicants"},
		{Name: "HrCreateApplicant", Description: "Applicants - applicant self service"},
		{Name: "HrCompMut", Description: "Wage entries"},
		{Name: "HrVarValue", Description: "Parameters"},
		{Name: "HrIllness", Description: "Absence entries"},
		{Name: "HrWellnessInSite", Description: "Close absence"},
		{Name: "HrAbsence", Description: "Leave entries"},
		{Name: "HrAbsCorrection", Description: "Leave balance corrections"},
		{Name: "HrDeclarationInSite", Description: "InSite declarations"},
		{Name: "HrCostCentre", Description: "Employer cost centres"},
		{Name: "HrCostCarrier", Description: "Add employer cost units"},
		{Name: "KnOrgEmrFun", Description: "Add employer jobs"},
		{Name: "HrJudgement", Description: "Employee assessments"},
		{Name: "HrTimeRegSocSec", Description: "Belgian time registration lines"},
	},
	"Order Management": {
		{Name: "FbSalesQuotation", Description: "Quotations"},
		{Name: "FbDirectInvoice", Description: "Desk/direct invoices"},
		{Name: "FbSales", Description: "Sales orders"},
		{Name: "FbFreeOrder", Description: "Release orders"},
		{Name: "FbPurch", Description: "Purchase orders"},
		{Name: "FbGoodsReceived", Description: "Receipts"},
		{Name: "FbDeliveryNote", Description: "Packing slips"},
		{Name: "FbItemArticle", Description: "Articles"},
		{Name: "FbProductGroup", Description: "Product group"},
		{Name: "FbProductGroupLines", Description: "Product group lines"},
		{Name: "FbWarTransferPrep", Description: "Preparation for transfer between warehouses"},
		{Name: "FbWarTransferOut", Description: "Warehouse transfer shipping slips"},
		{Name: "FbWarTransferIn", Description: "Warehouse transfer receipt slips"},
		{Name: "FbUnitBasicItem", Description: "Articles with multiple units"},
		{Name: "FbExtraBarcode", Description: "Extra barcodes for articles"},
		{Name: "FbUpdateAdB", Description: "Barcodes for dimension articles"},
		{Name: "FbComposition", Description: "Assembled items"},
		{Name: "AssemblyPrep", Description: "Assembly preparations"},
		{Name: "FbSalesPrice", Description: "Article sales prices"},
		{Name: "FbPurchPrice", Description: "Article purchase prices"},
		{Name: "FbItemCodeWarehouse", Description: "Warehouse allocations for article"},
		{Name: "FbItemCodeSupplier", Description: "Multiple suppliers for an article"},
		{Name: "FbBitVatTarifGroup", Description: "VAT rate group per item"},
		{Name: "FbStockMutation", Description: "Stock"},
	},
	"Projects": {
		{Name: "PtRealization", Description: "Actual costing"},
		{Name: "PtRealizationWeek", Description: "Actual costing per week"},
		{Name: "PtLinesToBeInvoiced", Description: "Actual costing to be invoiced"},
		{Name: "PtProject", Description: "Update projects and project phases"},
		{Name: "KnTeamMember", Description: "Teams and team members"},
		{Name: "KnQuotation", Description: "Cost estimate"},
		{Name: "PtProjectProgress", Description: "Project progress"},
		{Name: "FbInstalment", Description: "Invoice instalments"},
		{Name: "PtMonitor", Description: "Monitoring codes"},
		{Name: "PtConProjectForecast", Description: "Forecast per project"},
	},
	"Subscriptions": {
		{Name: "FbSubscription", Description: "Subscriptions and subscription lines"},
	},
}
