// DO NOT EDIT: generated by github.com/tim-online/go-afas-profit-rest/generate

package afas

func (api *API) FiEntryPar() *FiEntryParService {
	return &FiEntryParService{api: api}
}

type FiEntryParService struct {
	api *API
}
