// DO NOT EDIT: generated by github.com/tim-online/go-afas-profit-rest/generate

package afas

func (api *API) KnSalesRelationOrg() *KnSalesRelationOrgService {
	return &KnSalesRelationOrgService{api: api}
}

type KnSalesRelationOrgService struct {
	api *API
}
